In [9]:
# Export butterworth filter coefficients and history
import gym 
import numpy as np
import utils.import_envs
from stable_baselines3.common.utils import set_random_seed

seed = np.random.randint(2 ** 32 - 1, dtype="int64").item()
set_random_seed(seed)

for i in range(3):
    env = gym.make("A1GymEnv-v0", gait_frequency=1.5, deterministic=True)
    env.reset()
    obs = env.get_observation()
    sensors = env.all_sensors()
    print(obs['ReferenceGait_flatten'])
    print(sensors[-1].get_period())
    print(sensors[-1].cpg_system.get_state())


/home/daniel/anaconda3/envs/rl-baselines-zoo-cu113/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))


argv[0]=
[-1.  1.  1. -1.]
0.6666666666666666
[[ 0.45307429 -0.89147276]
 [-0.45307429  0.89147276]
 [-0.45307429  0.89147276]
 [ 0.45307429 -0.89147276]]
argv[0]=
[-1.  1.  1. -1.]
0.6666666666666666
[[-0.26458023 -0.96436368]
 [ 0.26458023  0.96436368]
 [ 0.26458023  0.96436368]
 [-0.26458023 -0.96436368]]
argv[0]=
[ 1. -1. -1.  1.]
0.6666666666666666
[[ 0.56717228  0.82359917]
 [-0.56717228 -0.82359917]
 [-0.56717228 -0.82359917]
 [ 0.56717228  0.82359917]]
