In [4]:
# Export butterworth filter coefficients and history
import gym 
import numpy as np
import utils.import_envs
env = gym.make("A1GymEnv-v0")

for i in range(3):
    env.reset()
    obs = env.get_observation()
    sensors = env.all_sensors()
    print(obs['ReferenceGait_flatten'])
    print(sensors[-1].period)


argv[0]=
[-1.  1.  1. -1.]
1.972138158743051
[-1.  1.  1. -1.]
1.9340097796256974
[ 1. -1. -1.  1.]
1.51281249054301


/home/daniel/anaconda3/envs/rl-baselines-zoo-cu113/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
